-- MySQL Script generated by MySQL Workbench
-- Thu Jan  8 19:29:29 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `pizza_price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_roles_idx` (`roles_id` ASC) ,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `total_price` DECIMAL NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders_has_users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders_has_users` (
  `orders_id` INT NOT NULL,
  `users_id` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `users_id`),
  INDEX `fk_orders_has_users_users1_idx` (`users_id` ASC) ,
  INDEX `fk_orders_has_users_orders1_idx` (`orders_id` ASC) ,
  CONSTRAINT `fk_orders_has_users_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_users_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_items` (
  `orders_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`orders_id`, `pizza_id`),
  INDEX `fk_orders_has_pizza_pizza1_idx` (`pizza_id` ASC) ,
  INDEX `fk_orders_has_pizza_orders1_idx` (`orders_id` ASC) ,
  CONSTRAINT `fk_orders_has_pizza_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_ingredients` (
  `pizza_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `ingredients_id`),
  INDEX `fk_pizza_has_ingredients_ingredients1_idx` (`ingredients_id` ASC) ,
  INDEX `fk_pizza_has_ingredients_pizza1_idx` (`pizza_id` ASC) ,
  CONSTRAINT `fk_pizza_has_ingredients_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`size` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_size` (
  `pizza_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `size_id`),
  INDEX `fk_pizza_has_size_size1_idx` (`size_id` ASC) ,
  INDEX `fk_pizza_has_size_pizza1_idx` (`pizza_id` ASC) ,
  CONSTRAINT `fk_pizza_has_size_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_size_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `mydb`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_tags` (
  `pizza_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `tags_id`),
  INDEX `fk_pizza_has_tags_tags1_idx` (`tags_id` ASC) ,
  INDEX `fk_pizza_has_tags_pizza1_idx` (`pizza_id` ASC) ,
  CONSTRAINT `fk_pizza_has_tags_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`tags` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
