-- MySQL Script generated by MySQL Workbench
-- Updated for Pizza Directory Application
-- Model: Pizza Directory    Version: 2.0

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb`;
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8mb4 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pizza`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `pizza_price` DECIMAL(10,2) NOT NULL,
  `image_path` VARCHAR(255) NULL,
  `description` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ingredients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`roles` ;

CREATE TABLE IF NOT EXISTS `mydb`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` ENUM('ROLE_USER', 'ROLE_ADMIN', 'ROLE_COOK', 'ROLE_COURIER') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `date_of_birth` DATE NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `address` VARCHAR(255) NULL,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `roles_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `fk_users_roles_idx` (`roles_id` ASC),
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_id`)
    REFERENCES `mydb`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`orders`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`orders` ;

CREATE TABLE IF NOT EXISTS `mydb`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `created_at` DATE NOT NULL,
  `updated_at` DATE NOT NULL,
  `total_price` DECIMAL(10,2) NOT NULL,
  `status` ENUM('PENDING', 'COOKING', 'READY', 'DELIVERING', 'DELIVERED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
  `users_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_orders_users1_idx` (`users_id` ASC),
  CONSTRAINT `fk_orders_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `mydb`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`size` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`order_items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`order_items` ;

CREATE TABLE IF NOT EXISTS `mydb`.`order_items` (
  `orders_id` INT NOT NULL,
  `pizza_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  `unit_price` DECIMAL(10,2) NULL,
  PRIMARY KEY (`orders_id`, `pizza_id`, `size_id`),
  INDEX `fk_orders_has_pizza_pizza1_idx` (`pizza_id` ASC),
  INDEX `fk_orders_has_pizza_orders1_idx` (`orders_id` ASC),
  INDEX `fk_order_items_size_idx` (`size_id` ASC),
  CONSTRAINT `fk_orders_has_pizza_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `mydb`.`orders` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_pizza_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_size`
    FOREIGN KEY (`size_id`)
    REFERENCES `mydb`.`size` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_ingredients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_ingredients` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_ingredients` (
  `pizza_id` INT NOT NULL,
  `ingredients_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `ingredients_id`),
  INDEX `fk_pizza_has_ingredients_ingredients1_idx` (`ingredients_id` ASC),
  INDEX `fk_pizza_has_ingredients_pizza1_idx` (`pizza_id` ASC),
  CONSTRAINT `fk_pizza_has_ingredients_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_ingredients_ingredients1`
    FOREIGN KEY (`ingredients_id`)
    REFERENCES `mydb`.`ingredients` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_size`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_size` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_size` (
  `pizza_id` INT NOT NULL,
  `size_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `size_id`),
  INDEX `fk_pizza_has_size_size1_idx` (`size_id` ASC),
  INDEX `fk_pizza_has_size_pizza1_idx` (`pizza_id` ASC),
  CONSTRAINT `fk_pizza_has_size_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_size_size1`
    FOREIGN KEY (`size_id`)
    REFERENCES `mydb`.`size` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`tags` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pizza_has_tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pizza_has_tags` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pizza_has_tags` (
  `pizza_id` INT NOT NULL,
  `tags_id` INT NOT NULL,
  PRIMARY KEY (`pizza_id`, `tags_id`),
  INDEX `fk_pizza_has_tags_tags1_idx` (`tags_id` ASC),
  INDEX `fk_pizza_has_tags_pizza1_idx` (`pizza_id` ASC),
  CONSTRAINT `fk_pizza_has_tags_pizza1`
    FOREIGN KEY (`pizza_id`)
    REFERENCES `mydb`.`pizza` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pizza_has_tags_tags1`
    FOREIGN KEY (`tags_id`)
    REFERENCES `mydb`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


-- -----------------------------------------------------
-- Initial Data
-- -----------------------------------------------------

-- Insert roles (ENUM values)
INSERT INTO `mydb`.`roles` (`name`) VALUES 
('ROLE_USER'), 
('ROLE_ADMIN'),
('ROLE_COOK'),
('ROLE_COURIER');

-- Insert sizes
INSERT INTO `mydb`.`size` (`name`, `price`) VALUES 
('Malá', 0.00),
('Stredná', 2.50),
('Veľká', 5.00);

-- Insert tags
INSERT INTO `mydb`.`tags` (`name`) VALUES 
('Vegetariánska'),
('Ostrá'),
('Obľúbená'),
('Novinka'),
('Klasická');

-- Insert sample ingredients
INSERT INTO `mydb`.`ingredients` (`name`, `price`) VALUES 
('Mozzarella', 1.50),
('Paradajková omáčka', 0.50),
('Pepperoni', 2.00),
('Šampiňóny', 1.00),
('Olivy', 1.00),
('Cibuľa', 0.50),
('Paprika', 1.00),
('Šunka', 2.00),
('Ananás', 1.50),
('Slanina', 2.50);

-- Insert sample pizzas
INSERT INTO `mydb`.`pizza` (`name`, `pizza_price`, `description`,`image_path`) VALUES

('Capricciosa', 10.99, 'Tradičná pizza so šunkou, šampiňónmi, mozzarellou a paradajkovou omáčkou', 'capricciosa.webp'),

('Carbonara', 11.49, 'Krémová pizza inšpirovaná carbonara s pancettou, syrom a jemnou smotanovou omáčkou', 'carbonara-pizza.webp'),

('Delicatezza Rustica', 12.49, 'Rustikálna pizza s prosciuttom, sušenými paradajkami, rukolou a parmezánom', 'delicatezza-rustica.webp'),

('Diavola Piccante', 11.99, 'Pikantná pizza s feferónkami, salámou a výraznou paradajkovou omáčkou', 'diavola-piccante.webp'),

('Funghi', 10.49, 'Jednoduchá a obľúbená pizza so šampiňónmi a mozzarellou', 'funghi.webp'),

('Funghi al Panna', 10.99, 'Pizza so šampiňónmi na jemnej smotanovej omáčke s mozzarellou', 'funghi-al-panna.webp'),

('Gluten Free Primavera', 12.99, 'Bezlepková pizza so sezónnou zeleninou, ľahkou omáčkou a mozzarellou', 'gluten-free-primavera.webp'),

('Havajská', 11.99, 'Kombinácia šunky a ananásu na paradajkovom základe s mozzarellou', 'hawaii-classic.webp'),

('La Crema Bianca', 11.79, 'Biela pizza so smotanovou omáčkou, syrom mozzarella a jemným cesnakom', 'la-crema-bianca.webp'),

('Margherita Classica', 9.99, 'Klasická talianska pizza s paradajkovou omáčkou, mozzarellou a bazalkou', 'margherita-classica.webp')
;

-- Link pizzas with ingredients
INSERT INTO `mydb`.`pizza_has_ingredients` (`pizza_id`, `ingredients_id`) VALUES 
(1, 1), (1, 2),
(2, 1), (2, 2), (2, 3),
(3, 1), (3, 2), (3, 8), (3, 9),
(4, 1), (4, 2), (4, 4), (4, 5), (4, 6), (4, 7),
(5, 1), (5, 2), (5, 3), (5, 8), (5, 10);

-- Link pizzas with sizes (all pizzas available in all sizes)
INSERT INTO `mydb`.`pizza_has_size` (`pizza_id`, `size_id`) VALUES 
(1, 1), (1, 2), (1, 3),
(2, 1), (2, 2), (2, 3),
(3, 1), (3, 2), (3, 3),
(4, 1), (4, 2), (4, 3),
(5, 1), (5, 2), (5, 3);

-- Link pizzas with tags
INSERT INTO `mydb`.`pizza_has_tags` (`pizza_id`, `tags_id`) VALUES 
(1, 1), (1, 5),
(2, 3), (2, 5),
(3, 4),
(4, 1),
(5, 2), (5, 3);

-- Insert staff users (password: Admin123! - BCrypt encoded)
INSERT INTO `mydb`.`users` (`first_name`, `last_name`, `email`, `password`, `created_at`, `updated_at`, `roles_id`) VALUES 
('Admin', 'Používateľ', 'admin@pizza.com', '$2a$10$VxgvANRs8lhXIJ4t11mR9evYy8FyTfjXYX8r.DDSxCh9nZOWSsE5G', CURDATE(), CURDATE(), 2),
('Kuchár', 'Hlavný', 'kuchar@pizza.com', '$2a$10$VxgvANRs8lhXIJ4t11mR9evYy8FyTfjXYX8r.DDSxCh9nZOWSsE5G', CURDATE(), CURDATE(), 3),
('Kuriér', 'Rýchly', 'kurier@pizza.com', '$2a$10$VxgvANRs8lhXIJ4t11mR9evYy8FyTfjXYX8r.DDSxCh9nZOWSsE5G', CURDATE(), CURDATE(), 4);
